apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "owner-label-injector.fullname" . }}
  labels:
    {{- include "owner-label-injector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "owner-label-injector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "owner-label-injector.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: {{ .Values.prometheus.scrape | quote }}
        prometheus.io/targets: {{ .Values.prometheus.targets | quote }}
    spec:
      serviceAccountName: {{ include "owner-label-injector.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          command:
          - /manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- with .Values.config.labels.prefix }}
          - name: LABEL_PREFIX
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.config.labels.supportGroupSuffix }}
          - name: SUPPORT_GROUP_SUFFIX
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.config.labels.serviceSuffix }}
          - name: SERVICE_SUFFIX
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.config.labels.dataSourceAnnotationSuffix }}
          - name: DATA_SOURCE_ANNOTATION_SUFFIX
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.config.helm.ownerConfigMapPrefix }}
          - name: OWNER_CONFIGMAP_PREFIX
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.config.helm.ownerConfigMapFallbackPrefix }}
          - name: OWNER_CONFIGMAP_FALLBACK_PREFIX
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.config.helm.supportGroupDataKey }}
          - name: SUPPORT_GROUP_DATA_KEY
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.config.helm.serviceDataKey }}
          - name: SERVICE_DATA_KEY
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.config.traversal.vicePresidentAnnotationKey }}
          - name: VICE_PRESIDENT_ANNOTATION_KEY
            value: {{ . | quote }}
          {{- end }}
          {{- with .Values.config.staticRules.rules }}
          - name: STATIC_RULES
            value: {{ dict "rules" . | toJson | quote }}
          {{- end }}
          volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
          ports:
            - name: http
              containerPort: 9443
              protocol: TCP
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "owner-label-injector.fullname" . }}
